import { useContext } from "react";
import { Header, Homepage } from "../components/index";
import Head from "next/head";
import AuthContext from "@/core/context";

export default function Home() {
  const { authData } = useContext(AuthContext);
  return (
    <>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {authData && (
        <div className="w-full h-full flex flex-col relative">
          <Header />
          <Homepage />
        </div>
      )}
    </>
  );
}
