import { useEffect, useMemo, useState } from "react";
import { Header, Homepage } from "../components/index";
import Head from "next/head";
import { useRouter } from "next/router";
import { IAuthData } from "@/core/model/auth.model";
import AuthContext from "@/core/context";
import Interceptor from "@/core/service/interceptor";

export default function Home() {
  const [authData, setAuthData] = useState<IAuthData | null>(null);
  const router = useRouter();

  const AuthState = useMemo(
    () => ({
      authData,
      setAuthData,
    }),
    [authData]
  );

  useEffect(() => {
    if (!localStorage.authData) {
      router.push("/login");
    } else {
      setAuthData(JSON.parse(localStorage.getItem("authData") as string));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return (
    <>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {authData && (
        <AuthContext.Provider value={AuthState}>
          <div className="w-full h-full flex flex-col relative">
            <Header />
            <Homepage />
          </div>
        </AuthContext.Provider>
      )}
      <Interceptor />
    </>
  );
}
